"""add mapping_confidence to imports

Revision ID: 6222fb964ef0
Revises: 5eaf53a14b90
Create Date: 2026-08-11 20:03:17.950171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6222fb964ef0'
down_revision: Union[str, Sequence[str], None] = '5eaf53a14b90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('imports', sa.Column('mapping_confidence', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('imports', 'mapping_confidence')
    # ### end Alembic commands ###
